export const VALID_CATEGORIES = [
  "Algorithms",
  "Data Structures",
  "Programming Fundamentals",
  "Object-Oriented Programming",
  "Functional Programming",
  "Logic Programming",
  "Software Engineering",
  "Software Design",
  "Design Patterns",
  "Requirements Engineering",
  "Testing",
  "Debugging",
  "Refactoring",
  "Version Control",
  "Computer Architecture",
  "Computer Organization",
  "Operating Systems",
  "Concurrent Programming",
  "Distributed Systems",
  "Networking",
  "Computer Security",
  "Cybersecurity",
  "Cryptography",
  "Databases",
  "Database Design",
  "SQL",
  "NoSQL",
  "Data Modeling",
  "Web Development",
  "Frontend Development",
  "Backend Development",
  "Full-Stack Development",
  "Mobile Development",
  "Cloud Computing",
  "DevOps",
  "Containerization",
  "Virtualization",
  "Compilers",
  "Programming Languages",
  "Formal Methods",
  "Automata Theory",
  "Computability",
  "Complexity Theory",
  "Discrete Mathematics",
  "Linear Algebra",
  "Probability",
  "Statistics",
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Science",
  "Data Analytics",
  "Information Retrieval",
  "Human-Computer Interaction",
  "User Experience",
  "Computer Graphics",
  "Game Development",
  "Parallel Computing",
  "High Performance Computing",
  "Real-Time Systems",
  "Embedded Systems",
  "Internet of Things",
  "IOT",
  "Numerical Computing",
  "Simulation",
  "Information Systems",
  "Digital Logic",
  "Theory of Computation",
  "Ethics in Computing",
  "Recursion",
  "Bit Manipulation",
  "Strings",
  "Arrays",
  "Brainteaser",
  "Hash Tables",
  "Sets",
  "Linked Lists",
  "Trees",
  "Graphs",
  "Stacks",
  "Queues",
  "Heaps",
  "Priority Queues",
  "Binary Search",
  "Sorting",
  "Dynamic Programming",
  "Greedy Algorithms",
  "Backtracking & Recursion",
  "Two Pointers",
  "Sliding Window",
  "Depth-First Search",
  "Breadth-First Search",
  "Union-Find"
];
